[
  # lib/qx/export/openqasm/parser.ex is generated by nimble_parsec from the
  # OpenQASM 3 grammar (mix.exs `parsec:` combinators). Dialyzer flags several
  # of the generated `program__NNNN/6` helper clauses as unreachable — an
  # artifact of the generated dispatch table, not dead application code.
  {"lib/qx/export/openqasm/parser.ex", :unused_fun},

  # @ibm_retry_delay is `Application.compile_env(:qx, :ibm_retry_delay, nil)`
  # — nil in :dev/:prod (Req's default backoff applies), a real integer only
  # in :test (keeps the transient-retry test fast). Dialyzer analyzes a
  # single compiled env (:dev) where the attribute is statically nil, so it
  # sees the `is_integer(delay)` clause in maybe_put_retry_delay/1 as
  # unreachable — true for this build, not for :test's.
  {"lib/qx/hardware/ibm.ex", :pattern_match_cov}
]
