# Phase 1 of the API consistency review (spec/api-design-principles.md §10).
# Emits one markdown row per function on the declared tier 1/2 surface.
#
#   mix run .claude/plans/api-consistency-review/api_inventory.exs

defmodule ApiInventory do
  @tier1 [Qx]
  @tier2 [
    Qx.QuantumCircuit,
    Qx.Operations,
    Qx.Patterns,
    Qx.Simulation,
    Qx.SimulationResult,
    Qx.Step,
    Qx.StateInit,
    Qx.Math,
    Qx.Draw,
    Qx.Export.OpenQASM,
    Qx.Hardware,
    Qx.Hardware.Config,
    Qx.Behaviours.QuantumState
  ]

  def run(out_path) do
    rows =
      Enum.flat_map(@tier1, &module_rows(&1, 1)) ++
        Enum.flat_map(@tier2, &module_rows(&1, 2))

    header = """
    # API inventory — tier 1/2 surface (generated)

    Generated by `api_inventory.exs` from `Code.fetch_docs/1` +
    `Code.Typespec.fetch_specs/1`. One row per exported function.
    `delegate` is the `defdelegate` target when the entry is a facade
    delegate. Doc: `yes` / `NONE` / `hidden`.

    | Tier | Module | Function | Signature | Doc | Spec | Deprecated | Delegates to |
    |---|---|---|---|---|---|---|---|
    """

    body = Enum.map_join(rows, "\n", &row_to_md/1)

    stats = summarize(rows)
    File.write!(out_path, header <> body <> "\n\n" <> stats)
    IO.puts("#{length(rows)} rows -> #{out_path}")
    IO.puts(stats)
  end

  defp module_rows(mod, tier) do
    {:module, ^mod} = Code.ensure_loaded(mod)

    specs =
      case Code.Typespec.fetch_specs(mod) do
        {:ok, list} -> MapSet.new(list, fn {{name, arity}, _} -> {name, arity} end)
        :error -> MapSet.new()
      end

    case Code.fetch_docs(mod) do
      {:docs_v1, _, :elixir, _, _moduledoc, _meta, docs} ->
        for {{:function, name, arity}, _anno, sigs, doc, meta} <- docs do
          %{
            tier: tier,
            module: inspect(mod),
            fun: "#{name}/#{arity}",
            sig: List.first(sigs) || "#{name}/#{arity}",
            doc: doc_status(doc),
            spec: MapSet.member?(specs, {name, arity}),
            deprecated: meta[:deprecated] || "",
            delegate: delegate_target(meta)
          }
        end
        |> Enum.sort_by(& &1.fun)

      other ->
        raise "Code.fetch_docs failed for #{inspect(mod)}: #{inspect(other)}"
    end
  end

  defp doc_status(:hidden), do: "hidden"
  defp doc_status(:none), do: "NONE"
  defp doc_status(%{}), do: "yes"

  defp delegate_target(%{delegate_to: {m, f, a}}), do: "#{inspect(m)}.#{f}/#{a}"
  defp delegate_target(_), do: ""

  defp row_to_md(r) do
    sig = r.sig |> String.replace("|", "\\|")

    "| #{r.tier} | #{r.module} | `#{r.fun}` | `#{sig}` | #{r.doc} | " <>
      "#{if r.spec, do: "yes", else: "NONE"} | #{r.deprecated} | #{r.delegate} |"
  end

  defp summarize(rows) do
    total = length(rows)
    no_doc = Enum.count(rows, &(&1.doc == "NONE"))
    hidden = Enum.count(rows, &(&1.doc == "hidden"))
    no_spec = Enum.count(rows, &(!&1.spec))
    deprecated = Enum.count(rows, &(&1.deprecated != ""))
    t1 = Enum.count(rows, &(&1.tier == 1))

    """
    ## Totals

    - functions: #{total} (tier 1: #{t1}, tier 2: #{total - t1})
    - missing @doc: #{no_doc}; @doc false: #{hidden}; missing @spec: #{no_spec}; deprecated: #{deprecated}
    """
  end
end

ApiInventory.run(".claude/plans/api-consistency-review/research/inventory.md")
